name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/henokv/laravel-docker/laravel-docker:$(date +%s)
    - name: Push image
      run: docker push docker.pkg.github.com/henokv/laravel-docker/laravel-docker:$(date +%s)
